context:
  name: pyhs3
  version: "0.0.1"
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ec1ffe8c58f699407791fc1e24daa07b151c03821c66c4dc6af39c770000a3f4

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ==${{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
      - pyhs3
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/scipp-atlas/pyhs3
  summary: 'pure-Python HS3 implementation with tensors and autodiff'
  description: |
    pyHS3 is a pure-python implementation of the HS3 sepcification
    that provides a callable pdf for statistical inference.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  documentation: https://pyhs3.readthedocs.io/
  repository: https://github.com/scipp-atlas/pyhs3

extra:
  recipe-maintainers:
    - kratsg
